#! /bin/bash

scrot 'screenshot_%Y-%m-%d_%H-%M-%S.jpg' -e 'mv $f ~/images/screenshots/' -u > /dev/null 2>&1
RESULT=$?
[ $RESULT -eq 0 ] && dunstify "Screenshot saved to:" "~/images/screenshots"
[ $RESULT -ne 0 ] && dunstify "Error taking screenshot"
