#!/usr/bin/env bats
# Completeness guard for the tmux cheatsheet overlay (prefix Alt-\).
#
# The overlay is generated by parsing #cs annotations out of the tmux conf
# files, so "shows all my keybinds" is only true if every bind is annotated.
# `cheatsheet.py --lint` enforces exactly that — and that the two OS keys files
# stay in sync — using the same parser that renders the overlay. These tests
# wrap it so `make test` fails loudly when a new bind is added without a #cs
# entry, or when the macOS/Linux annotations drift apart.

CHEATSHEET="${BATS_TEST_DIRNAME}/../tmux/cheatsheet.py"

@test "cheatsheet --lint: every bind is annotated and macOS/Linux stay in sync" {
  run python3 "$CHEATSHEET" --lint
  [ "$status" -eq 0 ]
}

@test "cheatsheet render: produces sections and the trigger's own entry" {
  run python3 "$CHEATSHEET"
  [ "$status" -eq 0 ]
  [[ "$output" == *"Pane focus"* ]]
  [[ "$output" == *"prefix Alt-\\"*"this cheatsheet"* ]]
}
