#!/usr/bin/env python3
"""Render (or lint) the tmux keybinding cheatsheet.

The cheatsheet shown by the `prefix Alt-\\` overlay is generated by parsing
`#cs` annotation comments out of .tmux.conf and the OS-matching keys file, so
the displayed list stays in lockstep with the real bindings.

Annotation format (also documented at the top of each .conf file):

    #cs <Section name>              a section header (no '|')
    ... #cs <key> | <description>   an entry — trailing on a bind line, or
                                    standalone (for built-in defaults that
                                    aren't bound in the conf)
    #cs-skip-begin / #cs-skip-end   exempt a block of repetitive binds (e.g.
                                    the 10 digit selectors) from the lint; they
                                    are covered by one grouped entry instead.
    ... bind …   #cs-skip          exempt a single bind (multi-line, or one
                                    covered by a nearby grouped/standalone
                                    entry) from the lint.

Recognition rules (these are what keep this doc block itself from parsing):
  - a standalone section/entry line is one whose stripped text starts with
    "#cs " — doc lines start with "# " so they're ignored;
  - a trailing entry is a `bind`/`bind-key` line containing "#cs ".

Usage:
    cheatsheet.py            render the cheatsheet for the current OS (colour
                             auto-enables on a TTY; honours NO_COLOR)
    cheatsheet.py --color    force colour (used by the popup, which pipes to
                             `less -R` so stdout isn't a TTY); --no-color forces off
    cheatsheet.py --lint     check annotation coverage + macOS/Linux parity
                             (exit 0 = clean, 1 = problems, printed to stderr)
"""

import os
import platform
import re
import sys
from pathlib import Path

# Truecolor (catppuccin mocha) for the rendered sheet — `less -R` passes these
# through. Descriptions stay uncoloured so they use the terminal's own fg.
RESET = "\033[0m"
BOLD = "\033[1m"


def _rgb(r, g, b):
    return f"\033[38;2;{r};{g};{b}m"


TITLE = _rgb(203, 166, 247)   # mauve
LEGEND = _rgb(108, 112, 134)  # overlay0
HEADER = _rgb(137, 180, 250)  # blue
KEY = _rgb(250, 179, 135)     # peach
SEP = _rgb(88, 91, 112)       # surface2

HERE = Path(__file__).resolve().parent
TMUX_CONF = HERE / ".tmux.conf"
KEYS_MACOS = HERE / "keys-macos.conf"
KEYS_LINUX = HERE / "keys-linux.conf"

MARKER = "#cs "

# A bind line whose command matches one of these is intentionally unannotated
# (internal plumbing, not a user-facing keybind). Everything else must carry a
# #cs entry or sit inside a #cs-skip block.
INTERNAL_SKIP = (
    re.compile(r"\bsend-prefix\b"),
)

BIND_RE = re.compile(r"^\s*bind(-key)?\b")


def _os_keys_file():
    return KEYS_MACOS if platform.system() == "Darwin" else KEYS_LINUX


def parse(path):
    """Return (sections, violations) for one .conf file.

    sections is a list of (name, [(key, desc), ...]) in first-encounter order;
    a section reappearing under the same name merges into the existing bucket.
    violations is a list of "path:lineno  <command>" for bind lines that lack a
    #cs entry, aren't inside a #cs-skip block, and aren't internal plumbing.
    """
    order = []
    by_name = {}
    violations = []
    current = None
    in_skip = False

    def bucket(name):
        if name not in by_name:
            by_name[name] = []
            order.append(name)
        return by_name[name]

    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        stripped = raw.strip()

        if stripped == "#cs-skip-begin":
            in_skip = True
            continue
        if stripped == "#cs-skip-end":
            in_skip = False
            continue

        is_bind = bool(BIND_RE.match(raw))

        # Standalone section/entry: stripped text begins with the marker.
        if stripped.startswith(MARKER):
            payload = stripped[len(MARKER):].strip()
            if "|" in payload:
                key, desc = (p.strip() for p in payload.split("|", 1))
                bucket(current if current else "Misc").append((key, desc))
            else:
                current = payload
            continue

        # Trailing entry on a bind line.
        if is_bind and MARKER in raw:
            payload = raw.split(MARKER, 1)[1].strip()
            if "|" in payload:
                key, desc = (p.strip() for p in payload.split("|", 1))
                bucket(current if current else "Misc").append((key, desc))
            continue

        # An unannotated bind line is a lint violation unless it's skipped
        # (inside a #cs-skip block, or carrying an inline #cs-skip token because
        # it's covered by a nearby grouped/standalone entry) or internal.
        if is_bind:
            if in_skip or "#cs-skip" in raw:
                continue
            if any(p.search(raw) for p in INTERNAL_SKIP):
                continue
            violations.append(f"{path.name}:{lineno}  {stripped}")

    return [(name, by_name[name]) for name in order], violations


def render(color=False):
    def paint(text, code, bold=False):
        if not color:
            return text
        return f"{BOLD if bold else ''}{code}{text}{RESET}"

    sections = []
    seen = {}
    for path in (_os_keys_file(), TMUX_CONF):
        for name, entries in parse(path)[0]:
            if name not in seen:
                seen[name] = []
                sections.append(name)
            seen[name].extend(entries)

    width = max(
        (len(k) for entries in seen.values() for k, _ in entries),
        default=0,
    )

    out = []
    out.append("  " + paint("tmux keybindings", TITLE, bold=True))
    out.append("  " + paint("prefix = Alt-c · a bare key (e.g. Alt-h) works directly ·", LEGEND))
    out.append("  " + paint("\"prefix X\" = tap prefix, then X · press q to close", LEGEND))
    out.append("")
    for name in sections:
        out.append(paint(f"  {name}", HEADER, bold=True))
        for key, desc in seen[name]:
            pad = " " * (width - len(key))  # pad on visible length, before colouring
            out.append(f"    {paint(key, KEY)}{pad}  {paint('│', SEP)}  {desc}")
        out.append("")
    return "\n".join(out)


def _want_color(argv):
    if os.environ.get("NO_COLOR"):
        return False
    if "--no-color" in argv:
        return False
    if "--color" in argv:
        return True
    return sys.stdout.isatty()


def lint():
    problems = []

    # 1. Coverage: every bind line annotated (or skipped) across all 3 files.
    for path in (TMUX_CONF, KEYS_MACOS, KEYS_LINUX):
        for v in parse(path)[1]:
            problems.append(f"unannotated bind (add #cs or wrap in #cs-skip): {v}")

    # 2. Parity: the two OS keys files must expose the same #cs entry set.
    def entry_set(path):
        return {
            (k, d)
            for _, entries in parse(path)[0]
            for k, d in entries
        }

    mac, lin = entry_set(KEYS_MACOS), entry_set(KEYS_LINUX)
    for k, d in sorted(mac - lin):
        problems.append(f"#cs entry in keys-macos.conf but not keys-linux.conf: {k} | {d}")
    for k, d in sorted(lin - mac):
        problems.append(f"#cs entry in keys-linux.conf but not keys-macos.conf: {k} | {d}")

    if problems:
        for p in problems:
            print(p, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    argv = sys.argv[1:]
    if "--lint" in argv:
        sys.exit(lint())
    print(render(color=_want_color(argv)))
